import { ABCard, AbilityCardTypes } from "../../api/types";
let RogueLibrary: ABCard[] = [];
export default RogueLibrary = [
  {
    id: "starterhood",
    title: "Cowl",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "chooseHealth1Ability1", userPrompt: "chooseHealth1Ability1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Item,
    effectString: "Choose: Health +1 -or- Ability +1",
  },
  {
    id: "starterarmor",
    title: "Light Armor",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addHealth1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Item,
    effectString: "Health +1",
  },
  {
    id: "starterbackstab",
    title: "Rogue Backstab",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addAttack1Draw1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Spell,
    effectString: "Attack +1, Draw 1 card",
  },
  {
    id: "starterboots",
    title: "Boots of Stealth",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addAbility1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Item,
    effectString: "Ability +1",
  },
  {
    id: "startercossbow",
    title: "Hand Crossbow",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addAttack1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Weapon,
    effectString: "Attack +1",
  },
  {
    id: "starterknife",
    title: "Knife",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "chooseAttack1Draw1", userPrompt: "chooseAttack1Draw1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Weapon,
    effectString: "Attack +1",
  },
  {
    id: "starterpickpocket",
    title: "Pickpocket",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addHealth1Ability1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Spell,
    effectString: "Health +1, Ability +1",
  },
  {
    id: "startersneak",
    title: "Rogue Sneak",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addAbility1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Spell,
    effectString: "Ability +1",
  },
  {
    id: "startersmoke",
    title: "Smoke Bomb",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addAttack1Ability1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Spell,
    effectString: "Ability +1, Attack +1",
  },
  {
    id: "startertools",
    title: "Lockpicking Tools",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "chooseAbility1Draw1", userPrompt: "chooseAbility1Draw1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Item,
    effectString: "Choose: Ability +1 -or- Draw 1 Card",
  },
];
