import { ABCard, AbilityCardTypes } from "../../api/types";
let WizardStartingDeck: ABCard[] = [];
export default WizardStartingDeck = [
  {
    id: "starterrobes",
    title: "Wizard Robes",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "chooseHealth1Ability1", userPrompt: "chooseHealth1Ability1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Item,
    effectString: "Choose: Health +1 -or- Ability +1",
  },
  {
    id: "starterwand",
    title: "Wand",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addAttack1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Weapon,
    effectString: "Attack +1",
  },
  {
    id: "starterspellbook",
    title: "Spellbook",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addAbility2" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Item,
    effectString: "Ability +2",
  },
  {
    id: "starterstaff",
    title: "Staff",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "chooseAttack1Ability1", userPrompt: "chooseAttack1Ability1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Weapon,
    effectString: "Choose: Attack +1 -or- Ability +1",
  },
  {
    id: "starterpet",
    title: "Pseudodragon",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addAttack1Ability1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Friend,
    effectString: "Attack +1, Ability +1",
  },
  {
    id: "starterfirespell",
    title: "Fire Spell",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addAttack1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Spell,
    effectString: "Attack +1",
  },
  {
    id: "starterminorheal",
    title: "Minor Heal",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addHealth1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Spell,
    effectString: "Health +1",
  },
  {
    id: "starterwizardfocus",
    title: "Focus",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addAbility1Draw1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Spell,
    effectString: "Ability +1, Draw 1",
  },
  {
    id: "starterwizardfocus",
    title: "Wizard Focus",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "addAbility1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Spell,
    effectString: "Ability +1",
  },
  {
    id: "startermagicarrow",
    title: "Magic Arrow",
    level: 1,
    cost: 0,
    ActiveEffect: { callback: "chooseAttack1Ability1", userPrompt: "chooseAttack1Ability1" },
    PassiveEffect: undefined,
    type: AbilityCardTypes.Spell,
    effectString: "Choose: Attack +1 -or- Ability +1",
  },
];
